# I believe this is necessary to get Jammit to run properly
embed_assets: off
# package_assets: always

javascripts:
    common:
        - public/javascripts/jquery-1.5.1.js
        - public/javascripts/*.js
    


stylesheets:
    common:
        - public/stylesheets/*.css
        # - public/stylesheets/scss/*.scss
    


